# Generated by Django 4.2 on 2023-04-30 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikefit', '0003_alter_medidas_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medidas',
            new_name='ModelCalculos',
        ),
    ]
