# Generated by Django 4.2.1 on 2023-05-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikefit', '0005_modelmural'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelcalculos',
            options={'verbose_name_plural': 'Cálculos'},
        ),
        migrations.AlterModelOptions(
            name='modelmural',
            options={'verbose_name': 'postagem', 'verbose_name_plural': 'postagens'},
        ),
        migrations.AlterField(
            model_name='modelcalculos',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
