# Generated by Django 4.2 on 2023-04-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cavalo', models.FloatField()),
                ('esterno', models.FloatField()),
                ('braco', models.FloatField()),
                ('email', models.FloatField()),
            ],
        ),
    ]
