# Generated by Django 4.2 on 2023-04-30 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikefit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
